### ISSUE TITLE
Gift Card operations are not available in this library

### ISSUE THREAD

**Issue by SKaistrenko** [recurly/recurly-client-node#156]
https://dev.recurly.com/docs/gift-card-object, https://dev.recurly.com/docs/create-gift-card etc. aren't exposed in this library. Is there any chance those can be added?

**Comment by douglasmiller** [comment]
@SKaistrenko: Unfortunately, gift cards are only supported in the v3 API when creating a purchase. Please reach out to support to indicate that you would like for full gift card support to be added to the v3 API. They will need to create a feature request for this/add a +1 to an existing request so that we can prioritize the feature.

**Comment by SKaistrenko** [comment]
It seems like we won't need it after all
