### ISSUE TITLE
#clientgetbillinginfo mentions you can use the account code, but returns an error

### ISSUE THREAD

**Issue by rafdizzle86** [recurly/recurly-client-node#38]
In the docs, it mentions I can use "account code" to look up billing info: https://recurly.github.io/recurly-client-node/#clientgetbillinginfo

> Parameters
> accountId (string) Account ID or code (use prefix: code- , e.g. code-bob ).

Unfortunately this results in an error for me:
```
> var billingInfo = recurlyConfig.client.getBillingInfo('rafi-0001')
> (node:11625) UnhandledPromiseRejectionWarning: RecurlyNotFoundError: Couldn't find Account with id = rafi-0001
```

**Comment by rafdizzle86** [comment]
Should the docs be updated? Or should the client be able to look up the account code?

**Comment by bhelx** [comment]
It takes an account id which is the account's id (druuid) or a friendly id. Here's the yet unreleased section of the upgrade doc that explains friendly ids:

-------

Since we no longer utilize “links” in our resources, it’s up to you to know which identifiers to use when calling the servers. There are two types of identifiers in V3:

    Druuids
    Friendly Ids

The Druuid is a base36 encoded integer and can be thought of as the internal identifier for a resource. The Friendly Id is a unique property on the resource which can also be used to identify the resource. It can be thought of as an external id. It’s often provided by you and is often human readble.

-------

So in your case, I think you need `recurlyConfig.client.getBillingInfo('code-rafi-0001')`

**Comment by rafdizzle86** [comment]
Makes sense! Thank you!
